### ISSUE TITLE
Plant selection sometimes blank in things page - see comments

### ISSUE THREAD

**Issue by MatthiasHarvey** [DillonHeins/Funge#145]
![1](https://cloud.githubusercontent.com/assets/8530889/19194913/9fdff160-8caf-11e6-9a89-b68159c1975d.PNG)
![2](https://cloud.githubusercontent.com/assets/8530889/19194916/a0b0d12c-8caf-11e6-9d74-ec22d85add9e.PNG)

This is due to this undefined option

**Comment by DillonHeins** [comment]
I just fixed this. Should work in latest commit :) let me know if it doesn't
